config/routes.rb
Html5Animation::Application.routes.draw do
  get "home/index"
  get "animation/index"
  get "animation/basic", :as => "basic"
  get "animation/shapes", :as => "shapes"
  root :to => "home#index"
end

app/controllers/animation_controller.rb
class AnimationController < ApplicationController
  def index
  end

  def basic
  end

  def shapes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/animation_helper.rb
module AnimationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/animation/basic.html.erb
<script type="application/javascript">

  function draw(){
    console.log("Drawing");
    var canvas = document.getElementById('tutorial');
    if (canvas.getContext){
      console.log("got context");
      var ctx = canvas.getContext('2d');
      ctx.fillStyle = "rgb(200,0,0)";
      ctx.fillRect( 10, 10, 55, 50 );

      ctx.fillStyle = "rgba(0, 0, 200, 0.5)";
      ctx.fillRect( 30, 30, 55, 50 );
    }
  }
</script>

<style type="text/css">
  canvas { border: 1px solid black; }
</style>

<% width = '150' %>
<% height = '150' %>
<body onload="draw();">
<p>This is your canvas at width: <%= width%> and height <%= height %></p>
<div>
<canvas id="tutorial" width="<%= width %>" height="<%= height%>"></canvas>
</div>
</body>

app/views/animation/index.html.erb
<canvas id="myCanvas" width="578" height="200"></canvas>
<div id="buttons">
  <input type="button" id="clear" value="Clear">
</div>
<script>
  var canvas = document.getElementById('myCanvas');
  var context = canvas.getContext('2d');

  // begin custom shape
  context.beginPath();
  <!-- context.moveTo(170, 80); -->
  context.bezierCurveTo(130, 100, 130, 150, 230, 150);
  <!-- context.bezierCurveTo(250, 180, 320, 180, 340, 150); -->
  <!-- context.bezierCurveTo(420, 150, 420, 120, 390, 100); -->
  <!-- context.bezierCurveTo(430, 40, 370, 30, 340, 50); -->
  <!-- context.bezierCurveTo(320, 5, 250, 20, 250, 50); -->
  <!-- context.bezierCurveTo(200, 5, 150, 20, 170, 80); -->

  // complete custom shape
  context.closePath();
  context.lineWidth = 5;
  context.strokeStyle = 'blue';
  context.stroke();

  // bind event handler to clear button
  document.getElementById('clear').addEventListener('click', function() {
  context.clearRect(0, 0, canvas.width, canvas.height);
  }, false);

</script>

app/views/animation/shapes.html.erb
<h4>Drawing Shapes</h4>

app/views/home/index.html.erb
<ul>
<li><%= link_to "Basic", basic_path %></li>
<li><%= link_to "Shapes", shapes_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Html5Animation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </style>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
      #buttons {
        position: absolute;
        top: 5px;
        left: 10px;
      }
      #buttons > input {
        padding: 10px;
        display: block;
        margin-top: 5px;
      }
    </style>
</head>
<body>

<%= yield %>

</body>
</html>